# Vlož do YAML editora jednej novej automatizácie. Nahraď entity a MAC.
alias: LG Ring – zvonček na TV
description: Zobudí LG TV a spustí aplikáciu Zvonček.
triggers:
  - trigger: state
    entity_id: binary_sensor.doorbell
    from: "off"
    to: "on"
conditions: []
actions:
  - if:
      - condition: template
        value_template: "{{ states('media_player.lg_webos_tv_75qned87a6b_beufljp') not in ['on', 'idle', 'playing', 'paused'] }}"
    then:
      - action: wake_on_lan.send_magic_packet
        data:
          mac: "1C:F4:3F:F0:07:F8"
      - wait_template: "{{ states('media_player.lg_webos_tv_75qned87a6b_beufljp') in ['on', 'idle', 'playing', 'paused'] }}"
        timeout: "00:00:30"
        continue_on_timeout: false
      - delay: "00:00:02"
  - action: webostv.command
    target:
      entity_id: media_player.lg_webos_tv_75qned87a6b_beufljp
    data:
      command: system.launcher/launch
      payload:
        id: sk.filip.doorbell
        params:
          action: doorbell
          duration: 15
          volume: 0.7
          message: "Pozri sa, kto prišiel na návštevu."
          label: "VCHODOVÉ DVERE"
          # camera: "http://192.168.1.50:8080/doorbell.m3u8"
          # cameraType: video
mode: restart
